### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by ehmatthes** [radiac/nanodjango#1]
Hi, this is a really interesting project! I have a little initial feedback from a first pass at setting it up locally, running tests, and starting to look at the code. 

Initial setup
---

Is there a reason your setup instructions don't look more like this?

```sh
git clone https://github.com/radiac/nanodjango.git
python -m venv .venv
source .venv/bin/activate
cd nanodjango
pip install -r requirements.txt
```

Notes:
- This removes the placeholder from the `clone` command.
- The convention seems to be `.venv` for naming virtual environments these days.
- I've always used the `source` command, and the . command is not working on my (macOS) system.
- Do you need to add `venv` (or `.venv`) to `.gitignore`?
- I also added `.DS_Store` to `.gitignore` for macOS.

Cleaning URL patterns
---

I think you can simplify `route()` in app.py:

```python
    def route(self, pattern: str):
        ...
        # We want to support Flask-like patterns which have leading / in its patterns.
        # Django does not use these, so strip them out.
        pattern = pattern.removeprefix("/")

        def wrapped(fn):
            ...
            # Register URL
            urlpatterns.append(
                url_path(pattern, string_view(fn), name=fn.__name__)
            )
            return fn

        return wrapped
```

I think the call to `removeprefix()` right away simplifies the method.

I'm happy to submit PRs, but wanted to share those thoughts first. I'm also not chasing PRs, so if you want to just make any changes based on this on your own I'm quite fine with that.

**Comment by radiac** [comment]
Thanks for your feedback!

Contributors setup: it's mostly that way because I've basically just copy-pasted the same contributors instructions from django-tagulous into every project for the past ~10 years :)  Good call, it's not really how I work these days, and I don't think its ever been a popular approach - worth updating.

Thanks for spotting the URL patterns issue too - one of those things where I've chopped and changed it a lot and didn't notice.

I won't have a chance to change it today - if you'd like to submit a PR then that would be very welcome, otherwise I should get on to it towards the end of the week.

Thanks again!

**Comment by ehmatthes** [comment]
I believe your steps are better when you're starting with a fork. I'm often just cloning repositories for exploratory reasons, without creating a fork. I won't touch the contributing docs for now. I'll submit a PR for the URL patterns, and then come back to the contributing docs with what worked for this first PR.
