### ISSUE TITLE
Using postgres

### ISSUE THREAD

**Issue by koaning** [radiac/nanodjango#27]
Is it the intention for this project to also be able to use postgres? The [docs highlight](https://nanodjango.readthedocs.io/en/latest/settings.html) a `SQLITE_DATABASE` variable which seems to suggest that postgres is not indended? 

Looking at the implementation, and docs, it seems like I can just pass `DATABASES` as well ... but figured I might double check if there is a reason not to use postgres here.

**Comment by radiac** [comment]
Yes, the goal is that nanodjango should support anything Django supports, including postgres.

Because a common use-case for this is quick experiments, I thought it made sense to default to an sqlite db; I added `SQLITE_DATABASE` as an easy way to give it a different filename when you have multiple scripts in the one dir. With hindsight that may have been better just picking up the app name, eg `counter.py` gets `counter.sqlite3`. Maybe I'll still do that at some point!

But, under the hood `SQLITE_DATABASE` just generates a standard `settings.DATABASES` object that uses sqlite. Although I've not got round to testing it, you should be able to pass a postgres `DATABASES` into `Django()` and have it work just as it would in a full Django project - for example, using the [django docs postgres setting](https://docs.djangoproject.com/en/5.1/ref/databases/#postgresql-connection-settings):

```
app = Django(
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "OPTIONS": {
                "service": "my_service",
                "passfile": ".my_pgpass",
            },
        }
    }
)
```

I'll close this for now, but do feel free to reopen if you run into any issues
