### ISSUE TITLE
models in external files

### ISSUE THREAD

**Issue by progressify** [radiac/nanodjango#47]
Is it possible to write models in another external file?
I understand the philosophy of a "one-file project" but if I have 4 or 5 models, for example, my "one-file" will grow and be difficult to maintain.

thanks

**Comment by radiac** [comment]
You could - the only catch at the moment is you can only define models after initialising `Django()`, so you'd need to import after that.

However, I'd advise against it - nanodjango really is all about the convenience of one file, for prototyping and sharing; when a project outgrows a single file, that's probably time to use the `convert` command.

**Comment by progressify** [comment]
> You could - the only catch at the moment is you can only define models after initialising `Django()`, so you'd need to import after that.


I already tried this approach, but the "app" variable probably is not visible in the imported file and the decorator: 
```
@app.admin
```
Raise an error.

**Comment by radiac** [comment]
Yes this is part of the issue - you need to create the `app=Django`, then your models, then your views - so that means probably an app.py imported by models.py imported by views.py, then run with `nanodjango run views.py`... but honestly at that point I have no idea what will happen - and it kinda defeats the point of nanodjango, you're already 90% of the way to a full project.

If it feels like it doesn't fit in one file, it's a sign you've outgrown what nanodjango is for, and probably need to run the `nanodjango convert` command.

**Comment by progressify** [comment]
oook, thank you :)
