### ISSUE TITLE
Click bikeshedding

### ISSUE THREAD

**Issue by SmileyChris** [radiac/nanodjango#5]
Putting the action first seems more natural:
```
nanodjango run my_project.py
nanodjango convert my_project.py
```

Furthermore, I wonder if it would be better to drop the .py and just import the module (`nanodjango run my_project`)

**Comment by SmileyChris** [comment]
Also, maybe `nanodjango dev my_project` would run devserver, `nanodjango run my_project` actually starts the gunicorn process implicitly?

**Comment by radiac** [comment]
I agree, I've also been finding the argument order a bit counterintuitive lately. I originally used that order because I was going for as close to flask as possible, (ie `$ flask --app hello run`), but now the project has grown I'm not a fan.

Can also definitely make the `.py` bit optional, that would be a nice touch - but I think being able to point it at a file not in your cwd or pythonpath is a nice feature I'd like to keep.
